-
  name: Execute two commands on boston nodes
  hosts: web
  tasks:
    
#    -  name: Execute commands
#       command: yum update -y && yum upgrade -y
    
#    -  name: Execute install
#       yum:
#           name: httpd
#           state: present
    
    -  name: start web server
       service: 
               name: httpd
               state: started
